version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: weather_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U weather_user -d weather_db']
      interval: 30s
      timeout: 10s
      retries: 3

  # Weather Application
  weather-app:
    build: .
    container_name: weather_app
    restart: unless-stopped
    environment:
      # HTTP Server Configuration
      HOST: 0.0.0.0
      PORT: 8080
      # Database Configuration
      DB_HOST: postgres # Use the service name for internal communication
      DATABASE: weather_db
      USER: weather_user
      PASSWORD: weather_password
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs # Optional: for persistent logs

volumes:
  postgres_data:
    driver: local
